sim_time_ms: 30000
seed: 0
burn_in_ms: 1000  # Ignore first 1s for warm-up
verbose: true     # Print progress updates
debug: false      # Show batch formation details

# Router can be: round_robin | jsq2 | wjsq2
router: wjsq2
router_params:
  d_choices: 2

workload:
  arrival: poisson        # deterministic | poisson
  rate_rps: 120           # used for poisson
  interarrival_ms: 12.0   # used for deterministic

devices:
  # Two targets with different speeds/latencies
  - id: t0
    role: target
    weight: 1.0
    batch_window_ms: 6.0
    batch_size: 32
    verify_latency_ms: 8.0
  - id: t1
    role: target
    weight: 0.6
    batch_window_ms: 8.0
    batch_size: 48
    verify_latency_ms: 11.0

  # Three drafts generating requests
  - id: d0
    role: draft
  - id: d1
    role: draft
  - id: d2
    role: draft