sim_time_ms: 10000
seed: 7
verbose: false
trace_path: trace/example_trace.jsonl
mixed_batching: true
router: round_robin

workload:
  arrival: deterministic
  interarrival_ms: 1000

devices:
  - id: target_0
    role: target
    batch_size: 8
    batch_window_ms: 10
    decode_latency_per_token: 3.0
    prefill_latency_per_token: 1.0
  - id: draft_0
    role: draft
    capability: 1.0
    generation_latency_ms: 10.0
    burst_factor: 1.0

connections:
  - draft: draft_0
    target: target_0
    forward_latency_ms: 5.0
    response_latency_ms: 5.0
    acceptance_rate: 0.85
